name: Bundle Code on Release Branches

on:
  push:
    branches:
      - 'release/*'  # This matches any branch that starts with release/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2  # Updated to v2 for the latest features
      with:
        node-version: '18.20.2'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Print TypeScript version
      run: npx tsc --version

    - name: Bundle the code
      run: npm run build

    - name: List output files
      run: ls -l ./dist

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: benefits-plan-assessment
        path: ./dist/**/*