name: Bundle Code on Release Branches

on:
  push:
    branches:
      - 'release/*'  # This matches any branch that starts with release/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.20.2'

    - name: Install dependencies
      run: npm install

    - name: Print TypeScript version
      run: npx tsc --version

    - name: Bundle the code
      run: npm run build  # Make sure your package.json has a 'build' script

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: bundled-code
        path: ./dist  # Change to your specific build output path
